
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Motor,  motorA,          headMotor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool isWall(){
	int distanceInCm = 20;
	if(SensorValue [sonar] > distanceInCm){
		return false;
	}
	else{
		motor[motorB]=0;
		motor[motorC]=0;
		return true;
	}
}

void robotTurn(short m,short deg){///Must be deleted
	nMotorEncoder[m]=0;
  nMotorEncoderTarget[m]=deg;
  int power = 25;
  if(deg <0){
  	power *= -1;
  }
  motor[m]=power;

  while(nMotorRunState(m) != runStateIdle){}
}
void goOn(int whereTo){
	int distanceInCm = 25;
	while(SensorValue [sonar] > distanceInCm){
	}
}

void avoid(int whereTo,){
	if(whereTo < 0){
		nSyncedMotors = synchCB;
		nSyncedTurnRatio = -100;
		robotTurn(motorC, -180);
	}
	if(whereTo > 0){
		nSyncedMotors = synchBC;
		nSyncedTurnRatio = -100;
		robotTurn(motorB, 180);
	}
	robotTurn(motorA, whereTo);
	nSyncedMotors = synchNone;
	goOn(whereTo);
}

task main(){
	int way = -90;
	motor[motorB] = 25;
	motor[motorC] = 25;
	while (!isWall()){}
		avoid(way);
}
