#pragma config(Sensor, S1,     ColorBWSensor,  sensorColorNxtRED)
#pragma config(Sensor, S4,     BWSensor,       sensorLightActive)
#pragma config(Sensor, S4,     sonarSensor,         sensorSONAR)
#pragma config(Motor,  motorA,					MotorHead,		 tmotorMXT,	PIDControl, turnHead,	  encoder)
#pragma config(Motor,  motorB,          MotorLeft,     tmotorNXT, PIDControl, driveLeft,  encoder)
#pragma config(Motor,  motorC,          MotorRight,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
typedef struct{
	int Cent = 20;
}distance;

bool isWall(distance dis){
	if(SensorValue[sonarSensor] > dis.Cent){
		return false;
	}
	else{
		motor[motorB] = 0;
		motor[motorC] = 0;
		return true;
	}
}
