#pragma config(Sensor, S1,     CSensor,  sensorColorNxtRED)
#pragma config(Sensor, S4,     BWSensor,       sensorLightActive)
#pragma config(Motor,  motorB,          MotorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          MotorRight,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <display.c>
#include <position.c>
#include <PID.c>
#include <calibration.c>

task main()
{
	initPID(calibrate());
	wait1Msec(1000);
	startTask(startPID);
}
