#pragma config(Sensor, S1,     CSensor,  sensorColorNxtRED)
#pragma config(Sensor, S4,     BWSensor,       sensorLightActive)
#pragma config(Motor,  motorA,          MotorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          MotorRight,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int BWBlack = 35;
int BWWhite = 65;

int CBlack = 22;
int CWhite = 63;

float Kp = 0.40;
float Tp = 25;

int errorAmount (int inputValue) //Goes from BWWhite to BWBlack, so -15 to 15.
{
		return (inputValue - ((BWWhite + BWBlack) / 2));
}
task main()
{
	while(1)
	{
		int error = errorAmount(SensorValue[BWSensor]);
		if (error == 0)//right error being bigger means more whitespace to the right, so steer to the left.
		{
			motor[motorB] = Tp;
			motor[motorC] = Tp;
		}
		else
		{
			int Turn = Kp * error;
			motor[motorB] = Tp - Turn;
			motor[motorC] = Tp + Turn;
		}
	}
}
